// Maximum AND Value 

// Given an array arr[] of N positive elements. The task is to find the Maximum AND Value generated by any pair of element from the array.
// Note: AND is bitwise '&' operator.

// { Driver Code Starts
//Initial Template for C++
#include<bits/stdc++.h>
using namespace std;


 // } Driver Code Ends
//User function Template for C++
 
class Solution
{
    public:
    // Function for finding maximum AND value.
    int maxAND (int arr[], int n)
    {
        // Your code here
        int total{0};
        int count{0};
        bool re{false};
        for (int i=31;i>=0;i--){
            if (re)
                i++;
            for (int j=0;j<n;j++) {
                if ((arr[j]>>i)&1 && re==false)
                    count++;
                else if(((arr[j]>>i)&1)==0 && re)
                    arr[j]=0;
            }
            if (count==0)
                re=false;
            else if (count>=2){
                total+=int(pow(2,i));
                re=true;
            }
            count=0;
        }
        return total;
    }
};

// { Driver Code Starts.
 
// Driver function
int main()
{
    int t;
    cin>>t;//testcases
    while(t--)
    {
        int n;
        cin>>n;//input n
        int arr[n+5],i;
        
        //inserting elements
        for(i=0;i<n;i++)
        cin>>arr[i];
        Solution obj;
        //calling maxAND() function
        cout <<  obj.maxAND(arr,n)<<endl;
    }
    return 0;
}  // } Driver Code Ends